name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11-bullseye

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install tkinter
      run: |
        apt-get update
        apt-get install -y python3-tk
        python -c "import tkinter; print(tkinter)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest

    - name: Run linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black . --check
        
    - name: Run tests
      run: |
        pytest tests/
