name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Debug Python environment
      run: |
        python --version
        which python
        echo $PATH

    - name: Install tkinter
      run: |
        set -e  # Exit on error
        sudo apt-get update
        sudo apt-get install -y python3.11-tk
        python -c "import tkinter; print(tkinter)"  # Verify tkinter installation

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest

    - name: Run linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black . --check
        
    - name: Run tests
      run: |
        pytest tests/
