name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install tkinter
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        python -c "import tkinter; print(tkinter)"  # Verify tkinter installation

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Remove tkinter from requirements before installing
        grep -v "^tkinter" requirements.txt > requirements_filtered.txt
        pip install -r requirements_filtered.txt
        pip install flake8 black pytest

    - name: Run linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black . --check || echo "Formatting issues detected. Run 'black .' locally to fix them."
        
    - name: Run tests
      run: |
        pytest tests/
